### ISSUE TITLE
Getting started with Vue - Cancel button does not work

### ISSUE THREAD

**Issue by scara1701** [taniarascia/taniarascia.com#100]
Hi,

I'm a novice with vue.js and found your excellent article on the subject.
Unfortunatelly I have encountered an issue with the cancel routine. 

Upon clicking on edit a copy is made of the employee, to allow it to be restored if the user clicks cancel. However it seems that the employee object is referenced in the copy. So the edited values are also pushed through on the copy. 

Does Vue have a option to make a deep copy of the employee object?
I have tried using temporary values for the email and name properties, but these also change.

**Comment by taniarascia** [comment]
I'm sorry, I don't understand what the issue is.

**Comment by scara1701** [comment]
When I edit a value in the employeed table it does not revert to the original value when the cancel button is clicked.

**Comment by taniarascia** [comment]
If I go to https://taniarascia.github.io/vue-tutorial/, start editing something, and then press cancel, the original state is preserved.

**Comment by scara1701** [comment]
Ok, this is totally my fault...

I forgot to change the method on the cancel button from 'editing = null' to 'cancelEdit(employee)'... Thank you for replying! :)
