### ISSUE TITLE
Link to "Build a CRUD App in React with Hooks" is broken

### ISSUE THREAD

**Issue by luc4leone** [taniarascia/taniarascia.com#110]
In "Knowledge of React terminology: JSX, State, Components, Props, Lifecycle and Hooks" the word "Hooks" link is broken 👉 https://www.taniarascia.com/redux-react-guide/crud-app-in-react-with-hooks is a 404

**Comment by KonradStanski** [comment]
Fixed in https://github.com/taniarascia/taniarascia.com/pull/111
