### ISSUE TITLE
Link to /categories/javascript is incorrect

### ISSUE THREAD

**Issue by bdacoscos** [taniarascia/taniarascia.com#12]
Hi Tania, first off just want to say... huge fan of your articles!! 

I clicked through the link (https://www.taniarascia.com/categories/javascript) on your React Router article and it leads to your nifty 404 page. I believe the link should lead to "https://www.taniarascia.com/categories/java-script" ?

**Comment by taniarascia** [comment]
Oh man, I was just trying to figure out what happened there. Thanks, I'll fix it!
