### ISSUE TITLE
re: https://www.taniarascia.com/node-express-postgresql-heroku/

### ISSUE THREAD

**Issue by travisricks** [taniarascia/taniarascia.com#121]
Hello,
First off, thank you thank you thank you. Your site has been so helpful for me!

I don't know if it was something I was doing incorrectly, but this tutorial did not work for me until I removed the `ssl` requirement in the config file. I hate to admit it, but it took me like 5 hours to figure out that was the cause.

I just wanted to let you know in case something changed in how Heroku was working.

Thanks,
Travis

**Comment by taniarascia** [comment]
Hi, 

The SSL is set to:

```js
const isProduction = process.env.NODE_ENV === 'production'
```

Meaning in production, it should be true, and in development it should be false. This is correct, so what issue did you have?

**Comment by travisricks** [comment]
When I had this code:
```
const pool = new Pool({
  connectionString: isProduction ? process.env.DATABASE_URL : connectionString,
  ssl: isProduction,
})
```
I kept getting an error about a self signing certificate and then the Heroku app would shut down. When I removed `ssl: isProduction` it worked.
```
