### ISSUE TITLE
PHP router .htaccess

### ISSUE THREAD

**Issue by muv1** [taniarascia/taniarascia.com#126]
I am new to PHP router, so I was happy when I came across this page:

<https://taniarascia.com/the-simplest-php-router>

However this confused me:

> In the root of your project, create a `.htaccess` file that will redirect all
> requests to `index.php`.

after some looking it seems `.htaccess` is specific to Apache, whereas I am
just looking to use something like this:

<https://php.net/commandline.webserver>

Further, my issue was I need something similar to `StripPrefix`:

<https://golang.org/pkg/net/http#StripPrefix>

After much trouble, I came up with this:

~~~php
<?php
$s1 = '!^/PREFIX/!';
$s2 = $_SERVER['REQUEST_URI'];
$n1 = preg_match($s1, $s2);
if ($n1 == 1) {
   $s3 = preg_replace($s1, '/', $s2);
   header('Location: ' . $s3);
} else {
   return false;
}
~~~

Perhaps you could update the page to reflect some of these findings?

**Comment by taniarascia** [comment]
I can update it to mention that it requires Apache.
