### ISSUE TITLE
Missing ids for #hash-links

### ISSUE THREAD

**Issue by Aprillion** [taniarascia/taniarascia.com#139]
On pages with #links to other sections of a page, the target sections need an `id` (`<h2 id=...` or `<a name=...`) - looks like those got lost during webpage redesign...

Reproduction steps (Firefox 78.0 Win 10):
* go to a guide, e.g. https://www.taniarascia.com/overview-of-css-concepts/
* click on a local link, e.g. https://www.taniarascia.com/overview-of-css-concepts/#other-considerations (or https://www.taniarascia.com/redux-react-guide/#reducers)
* it should scroll to the relevant section, but currently the page scrolls to top

**Comment by taniarascia** [comment]
Thanks, I fixed it.
