### ISSUE TITLE
Duplicates in RSS feed

### ISSUE THREAD

**Issue by shreyasminocha** [taniarascia/taniarascia.com#141]
There seem to be some duplicates in the RSS feed at [`/rss.xml`](https://www.taniarascia.com/rss.xml), because some 60 posts suddenly showed up in my reader a couple of days back. Search for `How To Use Array Methods in JavaScript: Iteration Methods`, for instance. There seem to be three matches:

```xml
<item>
	<title>
		How To Use Array Methods in JavaScript: Iteration Methods
	</title>
	…
	<pubDate>Tue, 15 Aug 2017 00:00:00 GMT</pubDate>
	…
</item>
```

```xml
<item>
	<title>
		How To Use Array Methods in JavaScript: Iteration Methods
	</title>
	…
	<pubDate>Mon, 14 Aug 2017 00:00:00 GMT</pubDate>
	…
</item>
```

```xml
<item>
	<title>
		How To Use Array Methods in JavaScript: Iteration Methods
	</title>
	…
	<pubDate>Thu, 10 Aug 2017 00:00:00 GMT</pubDate>
	…
</item>
```

I may be mistaken, but `pubDate` seems to be the only difference in the three.

**Comment by taniarascia** [comment]
That is very strange. 😞  I'll look into it.

**Comment by taniarascia** [comment]
Still seeing duplicates @shreyasminocha? I noticed that I can't get my Google RSS feed to update properly, but if I paste the RSS feed in something new it works just fine.

**Comment by shreyasminocha** [comment]
> I noticed that I can't get my Google RSS feed to update properly, but if I paste the RSS feed in something new it works just fine.

Yeah, same. Looks like it's not an issue anymore. What fixed it?

**Comment by taniarascia** [comment]
Not sure. I put a limit on it and played around with a few things. Oh well, glad it's working now!
