### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by judicaelandria** [taniarascia/taniarascia.com#145]
The issue is when switching to the dark mode it has a little latency
![ezgif com-gif-maker](https://user-images.githubusercontent.com/46365844/92579191-8c881980-f295-11ea-9ad3-fb6aaaabdeac.gif)

**Comment by taniarascia** [comment]
Ah, yeah. I wanted to update the comments color on the fly as well, but apparently that's some blocking request. Better now?

**Comment by judicaelandria** [comment]
oh same thing, has 1s of latency I think
tested it on chrome

**Comment by taniarascia** [comment]
@judicaelandria Did you test it recently? Try again after a refresh, because I'm pretty sure I fixed the issue.

**Comment by judicaelandria** [comment]
I just test it now
on mobile

**Comment by judicaelandria** [comment]
here is a on chrome windows
![2020-09-09-20-39-30](https://user-images.githubusercontent.com/46365844/92634112-76517c00-f2dc-11ea-8e96-7438b8417c78.gif)
work fine on firefox

**Comment by taniarascia** [comment]
Thanks, I'll look into it.

**Comment by taniarascia** [comment]
I can't replicate it, I'll leave it here for a bit to see if there are others with the issue.
