### ISSUE TITLE
Takenote conclusion link error.

### ISSUE THREAD

**Issue by aminejafur** [taniarascia/taniarascia.com#147]
Hello, 

I don't know if I have the right to open this as an issue but couldn't find a better way to inform you about this link error in the [conclusion](https://www.taniarascia.com/building-takenote/#conclusion).

"**Laconia** the MVC PHP app" will take you to "Primitive" Repo.

By the way, I enjoyed the Article thanks for sharing!

**Comment by taniarascia** [comment]
Thanks, I'll fix it!
