### ISSUE TITLE
Patreon badge error in README.md

### ISSUE THREAD

**Issue by techCarpenter** [taniarascia/taniarascia.com#148]
# Patreon badge error

The current patreon badge isn't rendering properly. The url points to a heroku app that doesn't exist.

`https://img.shields.io/endpoint.svg?url=https://shieldsio-patreon.herokuapp.com/taniarascia&style=for-the-badge`

![image](https://user-images.githubusercontent.com/42778030/106767621-0f28c100-6609-11eb-842c-cedf38e1f7f1.png)

It looks like the project has been [moved to vercel](https://shieldsio-patreon.vercel.app/).

Based on your current badge, I think this is the correct markdown to render it

```markdown
[![Patreon donate button](https://img.shields.io/endpoint.svg?url=https://shieldsio-patreon.vercel.app/api?username=taniarascia&type=patrons&style=for-the-badge)](https://patreon.com/taniarascia "Support me on Patreon")
```

## Rendered Markdown:

[![Patreon donate button](https://img.shields.io/endpoint.svg?url=https://shieldsio-patreon.vercel.app/api?username=taniarascia&type=patrons&style=for-the-badge)](https://patreon.com/taniarascia "Support me on Patreon")

**Comment by techCarpenter** [comment]
I'd be happy to create a pull request. This is the first issue I've written (that I can think of)

**Comment by taniarascia** [comment]
Thanks @techCarpenter! I just went ahead and fixed it.
