### ISSUE TITLE
Where can I find similar image resources?

### ISSUE THREAD

**Issue by SketchK** [taniarascia/taniarascia.com#153]
Image resource like  [nav-floppy.png](https://github.com/taniarascia/taniarascia.com/blob/master/src/assets/nav-floppy.png), [nav-github.png](https://github.com/taniarascia/taniarascia.com/blob/master/src/assets/nav-github.png) is awesome, Where can I find similar image resources?
Thank you!

**Comment by taniarascia** [comment]
You will not be able to find similar image resources because I made them. You can also make your own, such as on [Pixel Art](https://www.pixilart.com/draw).
