### ISSUE TITLE
Theme Bug

### ISSUE THREAD

**Issue by Its-Just-Nans** [taniarascia/taniarascia.com#154]
I think the theme has a little problem when it is not set in `localStorage()`

As you can see in the picture below, the website start with a black header but a white central page.

It can be cool, but some words (created by React `<Link>`) appear white (see in the picture below : words `projects` and `writing` are hidden)

![output](https://user-images.githubusercontent.com/56606507/148986844-4833f62c-cffe-4678-91b1-e4b5df3711cb.gif)

**Comment by taniarascia** [comment]
Thanks! I fixed it.
