### ISSUE TITLE
How to make Highlight post?

### ISSUE THREAD

**Issue by sarmadgardezi** [taniarascia/taniarascia.com#159]
I really appreciate your work on theme. i made Highlights true but it shows nothing why ?

**Comment by taniarascia** [comment]
I'm sorry, I don't know what you're referring to.

**Comment by sarmadgardezi** [comment]
In your theme front page heading highlights are not displaying can you help me with that. in the post .md i use the header as highlight: true but still in the front page highlights section no highlights posts are displaying.
