### ISSUE TITLE
Bug Dark Theme 

### ISSUE THREAD

**Issue by khoirulaksara** [taniarascia/taniarascia.com#166]
Hello,
I found a bug when changing theme to dark mode.
thanks.
![chrome_FxNg9r6JS0](https://user-images.githubusercontent.com/57844594/210015441-402166c8-de7f-4b13-8abb-0ca5438b8170.gif)

**Comment by taniarascia** [comment]
I'm not sure what you're looking at. The design there is several months out of date. Unfortunately, I don't provide any support for tinkering.
