### ISSUE TITLE
Bug Comments

### ISSUE THREAD

**Issue by khoirulaksara** [taniarascia/taniarascia.com#167]
Hello,
comments area duplicated when click Heading link on post.

![Screen Recording 2022-12-31 at 01 39 06](https://user-images.githubusercontent.com/57844594/210102717-be2a617e-45f5-44b5-85ec-550c3ebab652.gif)

**Comment by taniarascia** [comment]
Thanks, I'll look into it.

**Comment by khoirulaksara** [comment]
you're welcome. 
I'm migrating from utterance to giscus and resolve this problem. maybe this could be an alternative. :)

**Comment by taniarascia** [comment]
I've fixed this issue for Utterance, thanks for bringing it to my attention.
