### ISSUE TITLE
index.php - I think REQUEST_URI should be used instead of REDIRECT_URL

### ISSUE THREAD

**Issue by tbenko73** [taniarascia/taniarascia.com#32]
$request = $_SERVER['REDIRECT_URL'];
//I think you wanted to do this here:
//$request = $_SERVER['REQUEST_URI'];

**Comment by taniarascia** [comment]
Please open a PR, because I don't know what this is referring to. Thanks!

**Comment by taniarascia** [comment]
Found it, I'll update.
