### ISSUE TITLE
Simple MVC App in Plain JavaScript possible bug when checking a checkbox

### ISSUE THREAD

**Issue by luc4leone** [taniarascia/taniarascia.com#40]
Hi @taniarascia :)

I was playing with the app here https://taniarascia.github.io/mvc/. There might be a small bug.

### Bug reproduction steps

1. Add 3 todos

<img src="https://user-images.githubusercontent.com/2797254/62165352-87c90600-b31e-11e9-8e63-8f179fedd850.png" width=300 />

2. Delete the second

<img src="https://user-images.githubusercontent.com/2797254/62165385-9ca59980-b31e-11e9-80e5-edaec7110d0b.png" width=300 />

3. Add forth todo

<img src="https://user-images.githubusercontent.com/2797254/62165413-adeea600-b31e-11e9-8a10-cab25aebc3a5.png" width=300 />

4. Check forth

<img src="https://user-images.githubusercontent.com/2797254/62165438-bcd55880-b31e-11e9-8e7c-bb7b087a5e61.png" width=300 />

Third todo should not be checked.

**Comment by taniarascia** [comment]
Thanks for all the details! Yes, the way I'm determining the id of the todo item needs to be refactored to fix this bug. I'll fix it soon :)

**Comment by taniarascia** [comment]
Fixed this, though I still need to do some additional refactoring.

**Comment by luc4leone** [comment]
>Fixed this

great! 

I played again with the app and I can confirm you that everything seems to work fine now.
