### ISSUE TITLE
Filtered out Markdown files showing in article count

### ISSUE THREAD

**Issue by robinmetral** [taniarascia/taniarascia.com#50]
Go to https://www.taniarascia.com/blog/ and try to search for "about" in the input.

No posts are showing, but the number of posts to the right says `1`.

## Why?

In addition to blog posts there are three markdown files in `content/pages`:

- `content/pages/resume.md`
- `content/pages/me.md`
- `content/pages/learn.md`

They are queried along with blog posts in this query:

https://github.com/taniarascia/taniarascia.com/blob/745bd8b023ff0e350da6d17622538ae8a4825534/src/pages/blog.js#L106-L131

They will never show up in the list of posts, because posts that don't have the `post` template specified in frontmatter are filtered out client-side in the `PostListing` component:

https://github.com/taniarascia/taniarascia.com/blob/745bd8b023ff0e350da6d17622538ae8a4825534/src/components/PostListing.js#L11

But they are still counted in the number of filtered posts:

https://github.com/taniarascia/taniarascia.com/blob/745bd8b023ff0e350da6d17622538ae8a4825534/src/pages/blog.js#L59

## Solution

Filter these out server-side with GraphQL. Then the client-side filtering in `PostListing` can even be removed.

Do you want a PR @taniarascia?

**Comment by taniarascia** [comment]
A PR would be great!
