### ISSUE TITLE
Edit button should be seen by readers ?

### ISSUE THREAD

**Issue by ochoadev** [taniarascia/taniarascia.com#88]
Hello Tania, 

I was looking at one of your posts at https://www.taniarascia.com and saw that you have an edit button.

I don't know if you want to show the edit button, but, for my use case scenario (I just read your posts) it's useless to have an edit button that redirects to the .md file of the post!  Simple readers should see this?

**Comment by taniarascia** [comment]
It is intentional. Anyone who wishes to edit can open a PR. Anyone who does not wish to edit can ignore the button. Much like the MDN docs.
