### ISSUE TITLE
Website logo

### ISSUE THREAD

**Issue by kirubiel** [taniarascia/taniarascia.com#9]
Great website. But I think the logo could use a change. Doesn't quite go with the design especially in night mode where it will show white edges around it breaking the clean design (not that much).

**Comment by taniarascia** [comment]
Yeah, I noticed that. I'm just using the Google emoji for floppy for now because I'm lazy, but maybe the Apple one works better with a dark background.

**Comment by kirubiel** [comment]
The font awesome icon fa-floppy-o looks great actually. You can try that.

**Comment by taniarascia** [comment]
I used the Apple emoji instead of Google and it looks better.
