### ISSUE TITLE
Running `yarn upgrade-interactive --latest`

### ISSUE THREAD

**Issue by tomasvn** [taniarascia/taniarascia.com#96]
https://github.com/taniarascia/taniarascia.com/blob/0f1285ed2e2868b91486e41bb13433789a6bd7a7/package.json#L84

Not sure if you know this, but yarn has a built-in command to update deps, `yarn upgrade-interactive --latest` :blush:

But, whatever works for you 👍

**Comment by taniarascia** [comment]
Cool, I'll update it to that.
